server:
  port: 8081
spring:
  application:
    name: family-gaetway
  profiles:
    active: pro

# 默认熔断超时时间30s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    hystrix1:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
