server:
  port: 8081
spring:
  application:
    name: family-gaetway
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: @max.file.size@
      # 设置总上传数据大小
      max-request-size: @max.request.size@
  main:
    allow-bean-definition-overriding: true

# 默认熔断超时时间30s
hystrix:
  command:
    hystrix1:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
        - /baidu
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 1m