server:
  port: 8080

# 查看routes信息 http://localhost:8081/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
#  config: classpath:logback-spring.xml
