server:
  port: 8081
spring:
  application:
    name: family-gaetway
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: @max.file.size@
      # 设置总上传数据大小
      max-request-size: @max.request.size@

# 默认熔断超时时间30s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    hystrix1:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

